// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlvuzrthzkuymicgsapq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sdnV6cnRoemt1eW1pY2dzYXBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NDI2OTgsImV4cCI6MjA1ODIxODY5OH0.BB4mAbLjeOqdHJTrRPhelPqKtcxwHAQTDd3pK-EnroU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);